# 安全帽检测数据集配置  
train: ../../datasets/safety_helmet/train/images
val: ../../datasets/safety_helmet/val/images  
test: ../../datasets/safety_helmet/test/images

# 类别数量
nc: 3

# 类别名称
names:
  0: person
  1: helmet  
  2: no_helmet
